// Generated by CoffeeScript 1.3.3
(function() {
  var PomodoroView, test;

  PomodoroView = (function() {

    function PomodoroView(plasmoid) {
      this.plasmoid = plasmoid;
    }

    PomodoroView.prototype.render = function() {
      var button, pomodoroBar, pomodoroTimer;
      this.layout = new LinearLayout(plasmoid);
      pomodoroTimer = new Label();
      button = new PushButton();
      pomodoroBar = new Meter();
      pomodoroBar.minimum = 0;
      pomodoroBar.maximum = config["work_length"];
      pomodoroBar.value = 0;
      pomodoroBar.meterType = "BarMeterHorizontal";
      layout.addItem(button);
      layout.addItem(pomodoroBar);
      layout.addItem(pomodoroTimer);
      return layout.size = new QSizeF(100, 100);
    };

    return PomodoroView;

  })();

  test = "test";

}).call(this);
