// Generated by CoffeeScript 1.3.3

goog.provide('mhlavac.plasmoid.Configuration');

mhlavac.plasmoid.Configuration = (function() {
  /**
      @type {plasmoid}
      @protected
  */

  Configuration.prototype.plasmoid = null;

  /**
      @param {plasmoid} plasmoid
      @constructor
  */


  function Configuration(plasmoid) {
    this.plasmoid = plasmoid;
  }

  Configuration.prototype.load = function() {
    var config, minute;
    minute = 60000;
    config = Array();
    config['work_length'] = this.plasmoid.readConfig('work_length') * minute;
    config['short_break_length'] = this.plasmoid.readConfig('short_break') * minute;
    config['long_break_length'] = this.plasmoid.readConfig('long_break') * minute;
    config['timetable'] = this.plasmoid.readConfig('timetable');
    return config;
  };

  return Configuration;

})();
