// Generated by CoffeeScript 1.3.3
var PomodoroView;

goog.provide('mhlavac.pomodoro.PomodoroView');

PomodoroView = (function() {

  function PomodoroView(plasmoid) {
    this.plasmoid = plasmoid;
  }

  PomodoroView.prototype.render = function() {
    var button, pomodoroBar, pomodoroTimer;
    this.layout = new LinearLayout(plasmoid);
    pomodoroTimer = new Label();
    button = new PushButton();
    pomodoroBar = new Meter();
    pomodoroBar.minimum = 0;
    pomodoroBar.maximum = 25;
    pomodoroBar.value = 0;
    pomodoroBar.meterType = "BarMeterHorizontal";
    this.layout.addItem(button);
    this.layout.addItem(pomodoroBar);
    this.layout.addItem(pomodoroTimer);
    return this.layout.size = new QSizeF(100, 100);
  };

  return PomodoroView;

})();
