// Generated by CoffeeScript 1.3.3
var label, layout;

goog.provide('mhlavac.pomodoro');

goog.require('mhlavac.pomodoro.PomodoroView');

goog.require('mhlavac.pomodoro.Notification');

layout = new LinearLayout(plasmoid);

label = new Label;

label.text = "test";

layout.addItem(label);

/*
@return Array
*/

