// Generated by CoffeeScript 1.3.3
(function() {
  var configChanged, workLength;

  configChanged = function() {};

  workLength = plasmoid.readConfig('work_length');

  plasmoid.include('notification.js');

  plasmoid.include('PomodoroView.js');

  print(test);

  plasmoid.readConfig('short_break');

  plasmoid.readConfig('long_break');

  plasmoid.configChanged = configChanged;

  /*
  @return Array
  */


}).call(this);
